### ISSUE TITLE
Footer mismatch

### ISSUE THREAD

**Issue by eko24ive** [vickyantre/Hw5#4]
Here is your footer:
![image](https://cloud.githubusercontent.com/assets/25591824/22896953/9224f53a-f22a-11e6-83a0-e0cece5a2f44.png)

Compare it to design:
![image](https://cloud.githubusercontent.com/assets/25591824/22896967/985f9b6c-f22a-11e6-874c-be62026f5efd.png)

Additional padding is required, also dots are missing for navigation links and horizontal line at top is missing too.

**Comment by vickyantre** [comment]
I am not assured that it is correct now, but i tried to fixed it.

**Comment by eko24ive** [comment]
dots are missing for navigation links

**Comment by vickyantre** [comment]
And now?

**Comment by eko24ive** [comment]
Yes, I see them !
Now the final push - add them without html, but using css `:before` pseudo class

**Comment by eko24ive** [comment]
Awesome, thats what I wanted to see !

**Comment by vickyantre** [comment]
done

**Comment by eko24ive** [comment]
Wonderfull !
